name: Build CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: STAGING

    defaults:
      run:
        working-directory: "cattleia-backend"

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Building using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn
      - run: yarn build
