# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: "cattleia-backend" # Here the path to the folder where lock file is located.

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn
      - run: yarn run build
      - run: pm2 stop all
      - run: pm2 delete all
      - run: pm2 save --force
      - run: pm2 start dist/index.js --name backend
      - run: cd ..
      - run: rm -rf cattleia-native-app
      - run: echo ok
