name: Test CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    environment: TEST
    
    env: 
      PORT: ${{ secrets.PORT }}
      JWT_ACCESS: ${{ secrets.JWT_ACCESS }}
      JWT_REFRESH: ${{ secrets.JWT_REFRESH }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
      INFURA_RINKEBY: ${{ secrets.INFURA_RINKEBY }}
      STRIPE_PUBLISHABLE: ${{ secrets.STRIPE_PUBLISHABLE }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
      TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
    
    defaults:
      run:
        working-directory: "cattleia-backend"

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn
      - run: yarn test
