name: Test CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment: DEV

    env:
      PORT: ${{ secrets.PORT }}
      JWT_ACCESS: ${{ secrets.JWT_ACCESS }}
      JWT_REFRESH: ${{ secrets.JWT_REFRESH }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
      INFURA_RINKEBY: ${{ secrets.INFURA_RINKEBY }}
      STRIPE_PUBLISHABLE: ${{ secrets.STRIPE_PUBLISHABLE }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
      TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}

    strategy:
      matrix:
        node: [16.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
